# Generated by Django 4.2.8 on 2023-12-10 08:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Title', models.CharField(max_length=255, verbose_name='Nomi')),
                ('Year', models.CharField(max_length=50, verbose_name='Yili')),
                ('Director', models.CharField(max_length=50, verbose_name='Derektori')),
                ('Plot', models.TextField(verbose_name='Izohi')),
                ('Country', models.CharField(max_length=13, verbose_name='Davalati')),
            ],
        ),
        migrations.CreateModel(
            name='Galarey',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='galarey/', verbose_name='Rasmi')),
                ('movie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Images', to='common.movie', verbose_name='Kinosi')),
            ],
        ),
    ]
