# Generated by Django 4.2.8 on 2023-12-10 12:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Footer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=50, verbose_name="To'liq ismi")),
                ('image', models.ImageField(upload_to='footer/', verbose_name='Rasmi')),
                ('description', models.TextField(verbose_name='Izoh')),
            ],
        ),
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=100, verbose_name="To'liq ismi")),
                ('image', models.ImageField(upload_to='player/', verbose_name='Rasmi')),
                ('created_at', models.DateField(auto_now=True)),
                ('description', models.TextField(verbose_name='Izoh')),
            ],
        ),
    ]
