# Generated by Django 4.2.8 on 2023-12-10 12:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Club',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Fudbol Klub')),
                ('image', models.ImageField(upload_to='club/')),
                ('created_at', models.DateField(auto_now=True)),
                ('description', models.TextField(verbose_name='Izoh')),
            ],
        ),
    ]
