# Generated by Django 4.2.8 on 2023-12-10 12:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0002_club'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='like',
            field=models.PositiveIntegerField(default=10, verbose_name='Like'),
        ),
    ]
